Revert back to using out of the box default Edge settings
citizensadvice/ca_testing pull request #46
Opened 2021-09-14 15:48 UTC by celonicolosi

This is a bugfix of the previous bugfix. The previous bugfix was not working properly when running tests local with Edge browser on Mac, and for the moment we can't use Microsoft Edge Beta for the automation, just the standard version.

**Bugfixes**
* Fixed load error in Selenium Webdriver Edge
  * We can not use Microsoft Edge Beta for automation
  * Revert back to using out of the box default Edge settings

2021-09-14 15:51 UTC, luke-hill commented
So this was actually an issue with Edge beta on Mac, not Edge wholesale on Mac.

The reason we did this is because Edge **only** exists in beta for Linux (Don't know why)

2021-09-14 15:53 UTC, luke-hill requested changes
Part of the explanation here is wrong. Mac can use beta, but we need to provide an additional property (Non-default), for this. Allowing people to provide additional properties to options e.t.c. is something we haven't yet allowed in our code, so for now let's just mention that Mac Edge had a slight bug.

2021-09-14 15:53 UTC, luke-hill commented on CHANGELOG.md
> +* Fixed load error in Selenium Webdriver Edge
* Fix Load error in Edge Options
  * Mac Edge was not properly processing the browser name by default

2021-09-15 13:03 UTC, luke-hill approved these changes

2021-09-15 13:04 UTC, luke-hill commented on lib/ca_testing/drivers/v4/options.rb
> -          # This is only needed before version 4.0 is stable
The EdgeHtml options (v3), is actually "more" stable than the EdgeChrome in v4 alpha.

EdgeChrome became the default in the rc1 release (But by then had some bug fixes), hence this plaster for all working perfectly.

2021-09-17 08:16 UTC, luke-hill approved these changes

2021-09-17 12:38 UTC, david-lake approved these changes

2021-09-17 12:42 UTC, merged